### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [0xricksanchez/like-dbg#162]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/0xricksanchez/like-dbg/assets/147402107/c16a315c-4a84-4f4d-a909-581444c7ef95)

**Comment by Kalyanimhala** [comment]
@0xricksanchez Kindly assign me this issue, I want to work on it.

**Comment by 0xricksanchez** [comment]
I appreciate the offer to help driving this project forward but solely adding an optional section to the readme clutters it even more is not something I see myself adding anytime soon if I’m the only person that works on the important things.
