### ISSUE TITLE
like_debugger appears to not be tagged correctly

### ISSUE THREAD

**Issue by R3zk0n** [0xricksanchez/like-dbg#165]
**Describe the bug**
It appears like on a clean build of like-dbg, the like_debugger docker image isn't being tagged sometimes, manually forcing the tag seems to break the the gdb script to the vm-linux. 

**To Reproduce**
1. - latest 
2. ./start_kgdb.py 
3. Standard 

**Expected behavior**
The script deploys and builds everything however often the docker image for the debugger isnt tagged, maybe a way to force the tagging to prevent this type of issues? 

**Screenshots**
<img width="1905" alt="image" src="https://github.com/0xricksanchez/like-dbg/assets/7919239/5769d917-c74e-4489-8a7c-a72e5a658108">

<img width="689" alt="image" src="https://github.com/0xricksanchez/like-dbg/assets/7919239/feaa0c60-3082-4816-bc4b-d8a82cef235e">

**Desktop (please complete the following information):**
Fill me in on the specs of your environment:
1. Operating system (e.g.: `cat /etc/os-release`) - 
<img width="752" alt="image" src="https://github.com/0xricksanchez/like-dbg/assets/7919239/3860af54-e69a-480f-a154-89ffc2a40f4f">

2. Python version (`python --version`) - python 3.10.4
3. Python packages (in your virtualenv: `pip freeze`)
3. Docker version (`docker --version`) 
<img width="494" alt="image" src="https://github.com/0xricksanchez/like-dbg/assets/7919239/d98209d9-4087-4502-ac9f-c1ce1b9f0c55">

**Additional context**
Tried it on multiple different systems, and virtual machines and appears to always be the same issue.

**Comment by 0xricksanchez** [comment]
@R3zk0n thanks for reporting this! I’ll take a look asap. I’m in the middle of moving so I hope I get around to fixing this soon. PRs welcome :)

**Comment by R3zk0n** [comment]
All good, will do my best to try to fix and then submit a PR, seems like the issue might be in the docker_runner.py

**Comment by R3zk0n** [comment]
OK! I am back so i think ive worked out the issue, 

it appears that the like_debugger isnt being tagged, and isnt installing gef correctly which cause it not be able to continue and use the remote debugging due gef-remote not being installed which makes sense, demostrated below

![image](https://github.com/0xricksanchez/like-dbg/assets/7919239/45131525-c2b1-40d0-b2f0-006de0482c79)

But mainly forcing the tagging of the container then installing gef, seems to make it work fine, 
![image](https://github.com/0xricksanchez/like-dbg/assets/7919239/52a1a0b0-c45b-456c-b4f2-28c1bb939844)
![image](https://github.com/0xricksanchez/like-dbg/assets/7919239/2876d1f1-e4e3-4f54-852b-db04345832a6)


Not exactly where to make the edit to force the gef to be installed, since in theory it should already be done but i guess doing a execute to confirm gef is installed in the container if not bail out would be useful, trying to find where to add it but once i do ill do a commit! :)

**Comment by 0xricksanchez** [comment]
The GEF "installation" happens in the `.dockerfile_dbg`: https://github.com/0xricksanchez/like-dbg/blob/main/.dockerfile_dbg#L44. There are no sanity checks if the command did not crash 😬

**Comment by R3zk0n** [comment]
Tried to use a bash script to replace the build but for some reason it runs in the wrong context, still working on it. :D

**Comment by R3zk0n** [comment]
#171 Hopefully this should be fixed now.
