### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by kalyani2003** [0xricksanchez/like-dbg#178]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/0xricksanchez/like-dbg/assets/84217977/c846fd6b-ffa5-4f7a-93a5-3a2b9467bde8)

**Comment by kalyani2003** [comment]
@0xricksanchez Kindly assign me this issue, I want to work on it! Thank You.

**Comment by 0xricksanchez** [comment]
closed via #162
