### ISSUE TITLE
Minimum python version is *probably* 3.9

### ISSUE THREAD

**Issue by apaolillo** [0xricksanchez/like-dbg#43]
I just tried with python3.8 on Ubuntu 20.04, and it fails with the following error:

`AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'`

Which is fixed by just using a more recent python interpreter (3.9 in my case).

**Comment by 0xricksanchez** [comment]
Oh absolutely! I totally forgot to adjust the README for that. That change came with the latest merge to main.. A README update is in the works where I’ll update the minimum requirement for the Python version!

thanks for the reminder :D!

**Comment by 0xricksanchez** [comment]
Fixed in #49
